application:
  name: "migration-demo-app"
  version: "1.0.0"
  environment: "production"

database:
  host: "db.example.com"
  port: 5432
  name: "appdb"
  ssl: true

cache:
  redis:
    host: "cache.example.com"
    port: 6379
    ttl: 3600

logging:
  level: "INFO"
  format: "json"
  output: "stdout"
